# @format

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development CI

on:
  pull_request:
    branches: ["development"]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CI checkout
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: CI setup
        run: yarn ci
      - name: CI build
        run: yarn build
      - name: CI lint
        run: yarn lint
      - name: Run tests
        run: yarn test
  